// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: attendance.sql

package store

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const deleteAttendance = `-- name: DeleteAttendance :exec
DELETE FROM meeting_attendance WHERE id = $1
`

func (q *Queries) DeleteAttendance(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteAttendance, id)
	return err
}

const listAttendance = `-- name: ListAttendance :many
SELECT id, meeting_date, kind, in_person, online, created_at
FROM meeting_attendance
WHERE meeting_date >= $1 AND meeting_date <= $2
ORDER BY meeting_date, kind
`

type ListAttendanceParams struct {
	FromDate time.Time `json:"from_date"`
	ToDate   time.Time `json:"to_date"`
}

func (q *Queries) ListAttendance(ctx context.Context, arg ListAttendanceParams) ([]MeetingAttendance, error) {
	rows, err := q.db.Query(ctx, listAttendance, arg.FromDate, arg.ToDate)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []MeetingAttendance{}
	for rows.Next() {
		var i MeetingAttendance
		if err := rows.Scan(
			&i.ID,
			&i.MeetingDate,
			&i.Kind,
			&i.InPerson,
			&i.Online,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertAttendance = `-- name: UpsertAttendance :one
INSERT INTO meeting_attendance (meeting_date, kind, in_person, online)
VALUES ($1, $2, $3, $4)
ON CONFLICT (meeting_date, kind) DO UPDATE SET
    in_person = EXCLUDED.in_person,
    online = EXCLUDED.online
RETURNING id, meeting_date, kind, in_person, online, created_at
`

type UpsertAttendanceParams struct {
	MeetingDate time.Time `json:"meeting_date"`
	Kind        string    `json:"kind"`
	InPerson    int32     `json:"in_person"`
	Online      *int32    `json:"online"`
}

func (q *Queries) UpsertAttendance(ctx context.Context, arg UpsertAttendanceParams) (MeetingAttendance, error) {
	row := q.db.QueryRow(ctx, upsertAttendance,
		arg.MeetingDate,
		arg.Kind,
		arg.InPerson,
		arg.Online,
	)
	var i MeetingAttendance
	err := row.Scan(
		&i.ID,
		&i.MeetingDate,
		&i.Kind,
		&i.InPerson,
		&i.Online,
		&i.CreatedAt,
	)
	return i, err
}
