// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: congregation.sql

package store

import (
	"context"
)

const getCongregation = `-- name: GetCongregation :one
SELECT id, name, number, midweek_day, weekend_day, updated_at
FROM congregation
WHERE id = 1
`

func (q *Queries) GetCongregation(ctx context.Context) (Congregation, error) {
	row := q.db.QueryRow(ctx, getCongregation)
	var i Congregation
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Number,
		&i.MidweekDay,
		&i.WeekendDay,
		&i.UpdatedAt,
	)
	return i, err
}

const updateCongregation = `-- name: UpdateCongregation :one
UPDATE congregation
SET name = $1,
    number = $2,
    midweek_day = $3,
    weekend_day = $4,
    updated_at = now()
WHERE id = 1
RETURNING id, name, number, midweek_day, weekend_day, updated_at
`

type UpdateCongregationParams struct {
	Name       string `json:"name"`
	Number     string `json:"number"`
	MidweekDay int16  `json:"midweek_day"`
	WeekendDay int16  `json:"weekend_day"`
}

func (q *Queries) UpdateCongregation(ctx context.Context, arg UpdateCongregationParams) (Congregation, error) {
	row := q.db.QueryRow(ctx, updateCongregation,
		arg.Name,
		arg.Number,
		arg.MidweekDay,
		arg.WeekendDay,
	)
	var i Congregation
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Number,
		&i.MidweekDay,
		&i.WeekendDay,
		&i.UpdatedAt,
	)
	return i, err
}
