// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: households.sql

package store

import (
	"context"

	"github.com/google/uuid"
)

const createHousehold = `-- name: CreateHousehold :one
INSERT INTO households (name, address, notes)
VALUES ($1, $2, $3)
RETURNING id, name, address, notes, created_at
`

type CreateHouseholdParams struct {
	Name    string `json:"name"`
	Address string `json:"address"`
	Notes   string `json:"notes"`
}

func (q *Queries) CreateHousehold(ctx context.Context, arg CreateHouseholdParams) (Household, error) {
	row := q.db.QueryRow(ctx, createHousehold, arg.Name, arg.Address, arg.Notes)
	var i Household
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Address,
		&i.Notes,
		&i.CreatedAt,
	)
	return i, err
}

const deleteHousehold = `-- name: DeleteHousehold :exec
DELETE FROM households WHERE id = $1
`

func (q *Queries) DeleteHousehold(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteHousehold, id)
	return err
}

const getHousehold = `-- name: GetHousehold :one
SELECT id, name, address, notes, created_at
FROM households
WHERE id = $1
`

func (q *Queries) GetHousehold(ctx context.Context, id uuid.UUID) (Household, error) {
	row := q.db.QueryRow(ctx, getHousehold, id)
	var i Household
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Address,
		&i.Notes,
		&i.CreatedAt,
	)
	return i, err
}

const listHouseholds = `-- name: ListHouseholds :many
SELECT id, name, address, notes, created_at
FROM households
ORDER BY name
`

func (q *Queries) ListHouseholds(ctx context.Context) ([]Household, error) {
	rows, err := q.db.Query(ctx, listHouseholds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Household{}
	for rows.Next() {
		var i Household
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Address,
			&i.Notes,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateHousehold = `-- name: UpdateHousehold :one
UPDATE households
SET name = $1, address = $2, notes = $3
WHERE id = $4
RETURNING id, name, address, notes, created_at
`

type UpdateHouseholdParams struct {
	Name    string    `json:"name"`
	Address string    `json:"address"`
	Notes   string    `json:"notes"`
	ID      uuid.UUID `json:"id"`
}

func (q *Queries) UpdateHousehold(ctx context.Context, arg UpdateHouseholdParams) (Household, error) {
	row := q.db.QueryRow(ctx, updateHousehold,
		arg.Name,
		arg.Address,
		arg.Notes,
		arg.ID,
	)
	var i Household
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Address,
		&i.Notes,
		&i.CreatedAt,
	)
	return i, err
}
