// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package store

import (
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Congregation struct {
	ID         int16     `json:"id"`
	Name       string    `json:"name"`
	Number     string    `json:"number"`
	MidweekDay int16     `json:"midweek_day"`
	WeekendDay int16     `json:"weekend_day"`
	UpdatedAt  time.Time `json:"updated_at"`
}

type FieldServiceReport struct {
	ID               uuid.UUID `json:"id"`
	PublisherID      uuid.UUID `json:"publisher_id"`
	Year             int16     `json:"year"`
	Month            int16     `json:"month"`
	SharedInMinistry bool      `json:"shared_in_ministry"`
	BibleStudies     int32     `json:"bible_studies"`
	Hours            *float64  `json:"hours"`
	AuxiliaryPioneer bool      `json:"auxiliary_pioneer"`
	Late             bool      `json:"late"`
	Remarks          string    `json:"remarks"`
	CreatedAt        time.Time `json:"created_at"`
	UpdatedAt        time.Time `json:"updated_at"`
}

type Household struct {
	ID        uuid.UUID `json:"id"`
	Name      string    `json:"name"`
	Address   string    `json:"address"`
	Notes     string    `json:"notes"`
	CreatedAt time.Time `json:"created_at"`
}

type MeetingAttendance struct {
	ID          uuid.UUID `json:"id"`
	MeetingDate time.Time `json:"meeting_date"`
	Kind        string    `json:"kind"`
	InPerson    int32     `json:"in_person"`
	Online      *int32    `json:"online"`
	CreatedAt   time.Time `json:"created_at"`
}

type Publisher struct {
	ID                   uuid.UUID   `json:"id"`
	HouseholdID          *uuid.UUID  `json:"household_id"`
	FirstName            string      `json:"first_name"`
	LastName             string      `json:"last_name"`
	Gender               string      `json:"gender"`
	Phone                string      `json:"phone"`
	Email                string      `json:"email"`
	BaptismDate          pgtype.Date `json:"baptism_date"`
	StartedPreachingDate pgtype.Date `json:"started_preaching_date"`
	SpiritualStatus      string      `json:"spiritual_status"`
	IsElder              bool        `json:"is_elder"`
	IsMinisterialServant bool        `json:"is_ministerial_servant"`
	IsRegularPioneer     bool        `json:"is_regular_pioneer"`
	IsSpecialPioneer     bool        `json:"is_special_pioneer"`
	ActivityStatus       string      `json:"activity_status"`
	CreatedAt            time.Time   `json:"created_at"`
}

type Session struct {
	ID        uuid.UUID `json:"id"`
	UserID    uuid.UUID `json:"user_id"`
	TokenHash string    `json:"token_hash"`
	ExpiresAt time.Time `json:"expires_at"`
	CreatedAt time.Time `json:"created_at"`
}

type User struct {
	ID           uuid.UUID `json:"id"`
	Email        string    `json:"email"`
	PasswordHash string    `json:"password_hash"`
	CreatedAt    time.Time `json:"created_at"`
}
