// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: publishers.sql

package store

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const countPublishers = `-- name: CountPublishers :one
SELECT count(*) FROM publishers
`

func (q *Queries) CountPublishers(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countPublishers)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createPublisher = `-- name: CreatePublisher :one
INSERT INTO publishers (
    household_id, first_name, last_name, gender, phone, email,
    baptism_date, started_preaching_date, spiritual_status,
    is_elder, is_ministerial_servant, is_regular_pioneer, is_special_pioneer
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13
)
RETURNING id, household_id, first_name, last_name, gender, phone, email,
    baptism_date, started_preaching_date, spiritual_status,
    is_elder, is_ministerial_servant, is_regular_pioneer, is_special_pioneer,
    activity_status, created_at
`

type CreatePublisherParams struct {
	HouseholdID          *uuid.UUID  `json:"household_id"`
	FirstName            string      `json:"first_name"`
	LastName             string      `json:"last_name"`
	Gender               string      `json:"gender"`
	Phone                string      `json:"phone"`
	Email                string      `json:"email"`
	BaptismDate          pgtype.Date `json:"baptism_date"`
	StartedPreachingDate pgtype.Date `json:"started_preaching_date"`
	SpiritualStatus      string      `json:"spiritual_status"`
	IsElder              bool        `json:"is_elder"`
	IsMinisterialServant bool        `json:"is_ministerial_servant"`
	IsRegularPioneer     bool        `json:"is_regular_pioneer"`
	IsSpecialPioneer     bool        `json:"is_special_pioneer"`
}

func (q *Queries) CreatePublisher(ctx context.Context, arg CreatePublisherParams) (Publisher, error) {
	row := q.db.QueryRow(ctx, createPublisher,
		arg.HouseholdID,
		arg.FirstName,
		arg.LastName,
		arg.Gender,
		arg.Phone,
		arg.Email,
		arg.BaptismDate,
		arg.StartedPreachingDate,
		arg.SpiritualStatus,
		arg.IsElder,
		arg.IsMinisterialServant,
		arg.IsRegularPioneer,
		arg.IsSpecialPioneer,
	)
	var i Publisher
	err := row.Scan(
		&i.ID,
		&i.HouseholdID,
		&i.FirstName,
		&i.LastName,
		&i.Gender,
		&i.Phone,
		&i.Email,
		&i.BaptismDate,
		&i.StartedPreachingDate,
		&i.SpiritualStatus,
		&i.IsElder,
		&i.IsMinisterialServant,
		&i.IsRegularPioneer,
		&i.IsSpecialPioneer,
		&i.ActivityStatus,
		&i.CreatedAt,
	)
	return i, err
}

const deletePublisher = `-- name: DeletePublisher :exec
DELETE FROM publishers WHERE id = $1
`

func (q *Queries) DeletePublisher(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deletePublisher, id)
	return err
}

const getPublisher = `-- name: GetPublisher :one
SELECT
    p.id, p.household_id, p.first_name, p.last_name, p.gender, p.phone, p.email,
    p.baptism_date, p.started_preaching_date, p.spiritual_status,
    p.is_elder, p.is_ministerial_servant, p.is_regular_pioneer, p.is_special_pioneer,
    p.activity_status, p.created_at,
    h.name AS household_name
FROM publishers p
LEFT JOIN households h ON h.id = p.household_id
WHERE p.id = $1
`

type GetPublisherRow struct {
	ID                   uuid.UUID   `json:"id"`
	HouseholdID          *uuid.UUID  `json:"household_id"`
	FirstName            string      `json:"first_name"`
	LastName             string      `json:"last_name"`
	Gender               string      `json:"gender"`
	Phone                string      `json:"phone"`
	Email                string      `json:"email"`
	BaptismDate          pgtype.Date `json:"baptism_date"`
	StartedPreachingDate pgtype.Date `json:"started_preaching_date"`
	SpiritualStatus      string      `json:"spiritual_status"`
	IsElder              bool        `json:"is_elder"`
	IsMinisterialServant bool        `json:"is_ministerial_servant"`
	IsRegularPioneer     bool        `json:"is_regular_pioneer"`
	IsSpecialPioneer     bool        `json:"is_special_pioneer"`
	ActivityStatus       string      `json:"activity_status"`
	CreatedAt            time.Time   `json:"created_at"`
	HouseholdName        *string     `json:"household_name"`
}

func (q *Queries) GetPublisher(ctx context.Context, id uuid.UUID) (GetPublisherRow, error) {
	row := q.db.QueryRow(ctx, getPublisher, id)
	var i GetPublisherRow
	err := row.Scan(
		&i.ID,
		&i.HouseholdID,
		&i.FirstName,
		&i.LastName,
		&i.Gender,
		&i.Phone,
		&i.Email,
		&i.BaptismDate,
		&i.StartedPreachingDate,
		&i.SpiritualStatus,
		&i.IsElder,
		&i.IsMinisterialServant,
		&i.IsRegularPioneer,
		&i.IsSpecialPioneer,
		&i.ActivityStatus,
		&i.CreatedAt,
		&i.HouseholdName,
	)
	return i, err
}

const listPublishers = `-- name: ListPublishers :many
SELECT
    p.id, p.household_id, p.first_name, p.last_name, p.gender, p.phone, p.email,
    p.baptism_date, p.started_preaching_date, p.spiritual_status,
    p.is_elder, p.is_ministerial_servant, p.is_regular_pioneer, p.is_special_pioneer,
    p.activity_status, p.created_at,
    h.name AS household_name
FROM publishers p
LEFT JOIN households h ON h.id = p.household_id
ORDER BY p.last_name, p.first_name
`

type ListPublishersRow struct {
	ID                   uuid.UUID   `json:"id"`
	HouseholdID          *uuid.UUID  `json:"household_id"`
	FirstName            string      `json:"first_name"`
	LastName             string      `json:"last_name"`
	Gender               string      `json:"gender"`
	Phone                string      `json:"phone"`
	Email                string      `json:"email"`
	BaptismDate          pgtype.Date `json:"baptism_date"`
	StartedPreachingDate pgtype.Date `json:"started_preaching_date"`
	SpiritualStatus      string      `json:"spiritual_status"`
	IsElder              bool        `json:"is_elder"`
	IsMinisterialServant bool        `json:"is_ministerial_servant"`
	IsRegularPioneer     bool        `json:"is_regular_pioneer"`
	IsSpecialPioneer     bool        `json:"is_special_pioneer"`
	ActivityStatus       string      `json:"activity_status"`
	CreatedAt            time.Time   `json:"created_at"`
	HouseholdName        *string     `json:"household_name"`
}

func (q *Queries) ListPublishers(ctx context.Context) ([]ListPublishersRow, error) {
	rows, err := q.db.Query(ctx, listPublishers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPublishersRow{}
	for rows.Next() {
		var i ListPublishersRow
		if err := rows.Scan(
			&i.ID,
			&i.HouseholdID,
			&i.FirstName,
			&i.LastName,
			&i.Gender,
			&i.Phone,
			&i.Email,
			&i.BaptismDate,
			&i.StartedPreachingDate,
			&i.SpiritualStatus,
			&i.IsElder,
			&i.IsMinisterialServant,
			&i.IsRegularPioneer,
			&i.IsSpecialPioneer,
			&i.ActivityStatus,
			&i.CreatedAt,
			&i.HouseholdName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listReportingPublishers = `-- name: ListReportingPublishers :many
SELECT
    p.id, p.household_id, p.first_name, p.last_name, p.gender, p.phone, p.email,
    p.baptism_date, p.started_preaching_date, p.spiritual_status,
    p.is_elder, p.is_ministerial_servant, p.is_regular_pioneer, p.is_special_pioneer,
    p.activity_status, p.created_at
FROM publishers p
WHERE p.spiritual_status IN ('unbaptized_publisher', 'publisher')
ORDER BY p.last_name, p.first_name
`

func (q *Queries) ListReportingPublishers(ctx context.Context) ([]Publisher, error) {
	rows, err := q.db.Query(ctx, listReportingPublishers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Publisher{}
	for rows.Next() {
		var i Publisher
		if err := rows.Scan(
			&i.ID,
			&i.HouseholdID,
			&i.FirstName,
			&i.LastName,
			&i.Gender,
			&i.Phone,
			&i.Email,
			&i.BaptismDate,
			&i.StartedPreachingDate,
			&i.SpiritualStatus,
			&i.IsElder,
			&i.IsMinisterialServant,
			&i.IsRegularPioneer,
			&i.IsSpecialPioneer,
			&i.ActivityStatus,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updatePublisher = `-- name: UpdatePublisher :one
UPDATE publishers SET
    household_id = $2,
    first_name = $3,
    last_name = $4,
    gender = $5,
    phone = $6,
    email = $7,
    baptism_date = $8,
    started_preaching_date = $9,
    spiritual_status = $10,
    is_elder = $11,
    is_ministerial_servant = $12,
    is_regular_pioneer = $13,
    is_special_pioneer = $14
WHERE id = $1
RETURNING id, household_id, first_name, last_name, gender, phone, email,
    baptism_date, started_preaching_date, spiritual_status,
    is_elder, is_ministerial_servant, is_regular_pioneer, is_special_pioneer,
    activity_status, created_at
`

type UpdatePublisherParams struct {
	ID                   uuid.UUID   `json:"id"`
	HouseholdID          *uuid.UUID  `json:"household_id"`
	FirstName            string      `json:"first_name"`
	LastName             string      `json:"last_name"`
	Gender               string      `json:"gender"`
	Phone                string      `json:"phone"`
	Email                string      `json:"email"`
	BaptismDate          pgtype.Date `json:"baptism_date"`
	StartedPreachingDate pgtype.Date `json:"started_preaching_date"`
	SpiritualStatus      string      `json:"spiritual_status"`
	IsElder              bool        `json:"is_elder"`
	IsMinisterialServant bool        `json:"is_ministerial_servant"`
	IsRegularPioneer     bool        `json:"is_regular_pioneer"`
	IsSpecialPioneer     bool        `json:"is_special_pioneer"`
}

func (q *Queries) UpdatePublisher(ctx context.Context, arg UpdatePublisherParams) (Publisher, error) {
	row := q.db.QueryRow(ctx, updatePublisher,
		arg.ID,
		arg.HouseholdID,
		arg.FirstName,
		arg.LastName,
		arg.Gender,
		arg.Phone,
		arg.Email,
		arg.BaptismDate,
		arg.StartedPreachingDate,
		arg.SpiritualStatus,
		arg.IsElder,
		arg.IsMinisterialServant,
		arg.IsRegularPioneer,
		arg.IsSpecialPioneer,
	)
	var i Publisher
	err := row.Scan(
		&i.ID,
		&i.HouseholdID,
		&i.FirstName,
		&i.LastName,
		&i.Gender,
		&i.Phone,
		&i.Email,
		&i.BaptismDate,
		&i.StartedPreachingDate,
		&i.SpiritualStatus,
		&i.IsElder,
		&i.IsMinisterialServant,
		&i.IsRegularPioneer,
		&i.IsSpecialPioneer,
		&i.ActivityStatus,
		&i.CreatedAt,
	)
	return i, err
}

const updatePublisherActivity = `-- name: UpdatePublisherActivity :exec
UPDATE publishers SET activity_status = $2 WHERE id = $1
`

type UpdatePublisherActivityParams struct {
	ID             uuid.UUID `json:"id"`
	ActivityStatus string    `json:"activity_status"`
}

func (q *Queries) UpdatePublisherActivity(ctx context.Context, arg UpdatePublisherActivityParams) error {
	_, err := q.db.Exec(ctx, updatePublisherActivity, arg.ID, arg.ActivityStatus)
	return err
}
