// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: reports.sql

package store

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const getPublisherForReport = `-- name: GetPublisherForReport :one
SELECT id, started_preaching_date, is_regular_pioneer, is_special_pioneer, spiritual_status
FROM publishers
WHERE id = $1
`

type GetPublisherForReportRow struct {
	ID                   uuid.UUID   `json:"id"`
	StartedPreachingDate pgtype.Date `json:"started_preaching_date"`
	IsRegularPioneer     bool        `json:"is_regular_pioneer"`
	IsSpecialPioneer     bool        `json:"is_special_pioneer"`
	SpiritualStatus      string      `json:"spiritual_status"`
}

func (q *Queries) GetPublisherForReport(ctx context.Context, id uuid.UUID) (GetPublisherForReportRow, error) {
	row := q.db.QueryRow(ctx, getPublisherForReport, id)
	var i GetPublisherForReportRow
	err := row.Scan(
		&i.ID,
		&i.StartedPreachingDate,
		&i.IsRegularPioneer,
		&i.IsSpecialPioneer,
		&i.SpiritualStatus,
	)
	return i, err
}

const listReportsForMonth = `-- name: ListReportsForMonth :many
SELECT
    r.id, p.id AS publisher_id, r.year, r.month, r.shared_in_ministry, r.bible_studies,
    r.hours, r.auxiliary_pioneer, r.late, r.remarks, r.created_at, r.updated_at,
    p.first_name, p.last_name, p.spiritual_status,
    p.is_regular_pioneer, p.is_special_pioneer
FROM publishers p
LEFT JOIN field_service_reports r
    ON r.publisher_id = p.id AND r.year = $1 AND r.month = $2
WHERE p.spiritual_status IN ('unbaptized_publisher', 'publisher')
ORDER BY p.last_name, p.first_name
`

type ListReportsForMonthParams struct {
	Year  int16 `json:"year"`
	Month int16 `json:"month"`
}

type ListReportsForMonthRow struct {
	ID               *uuid.UUID         `json:"id"`
	PublisherID      uuid.UUID          `json:"publisher_id"`
	Year             *int16             `json:"year"`
	Month            *int16             `json:"month"`
	SharedInMinistry *bool              `json:"shared_in_ministry"`
	BibleStudies     *int32             `json:"bible_studies"`
	Hours            *float64           `json:"hours"`
	AuxiliaryPioneer *bool              `json:"auxiliary_pioneer"`
	Late             *bool              `json:"late"`
	Remarks          *string            `json:"remarks"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
	FirstName        string             `json:"first_name"`
	LastName         string             `json:"last_name"`
	SpiritualStatus  string             `json:"spiritual_status"`
	IsRegularPioneer bool               `json:"is_regular_pioneer"`
	IsSpecialPioneer bool               `json:"is_special_pioneer"`
}

func (q *Queries) ListReportsForMonth(ctx context.Context, arg ListReportsForMonthParams) ([]ListReportsForMonthRow, error) {
	rows, err := q.db.Query(ctx, listReportsForMonth, arg.Year, arg.Month)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListReportsForMonthRow{}
	for rows.Next() {
		var i ListReportsForMonthRow
		if err := rows.Scan(
			&i.ID,
			&i.PublisherID,
			&i.Year,
			&i.Month,
			&i.SharedInMinistry,
			&i.BibleStudies,
			&i.Hours,
			&i.AuxiliaryPioneer,
			&i.Late,
			&i.Remarks,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.FirstName,
			&i.LastName,
			&i.SpiritualStatus,
			&i.IsRegularPioneer,
			&i.IsSpecialPioneer,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSharesForPublisher = `-- name: ListSharesForPublisher :many
SELECT year, month, shared_in_ministry
FROM field_service_reports
WHERE publisher_id = $1
  AND (year > $2 OR (year = $2 AND month >= $3))
  AND (year < $4 OR (year = $4 AND month <= $5))
ORDER BY year, month
`

type ListSharesForPublisherParams struct {
	PublisherID uuid.UUID `json:"publisher_id"`
	FromYear    int16     `json:"from_year"`
	FromMonth   int16     `json:"from_month"`
	ToYear      int16     `json:"to_year"`
	ToMonth     int16     `json:"to_month"`
}

type ListSharesForPublisherRow struct {
	Year             int16 `json:"year"`
	Month            int16 `json:"month"`
	SharedInMinistry bool  `json:"shared_in_ministry"`
}

func (q *Queries) ListSharesForPublisher(ctx context.Context, arg ListSharesForPublisherParams) ([]ListSharesForPublisherRow, error) {
	rows, err := q.db.Query(ctx, listSharesForPublisher,
		arg.PublisherID,
		arg.FromYear,
		arg.FromMonth,
		arg.ToYear,
		arg.ToMonth,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListSharesForPublisherRow{}
	for rows.Next() {
		var i ListSharesForPublisherRow
		if err := rows.Scan(&i.Year, &i.Month, &i.SharedInMinistry); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertReport = `-- name: UpsertReport :one
INSERT INTO field_service_reports (
    publisher_id, year, month, shared_in_ministry, bible_studies,
    hours, auxiliary_pioneer, late, remarks, updated_at
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, now()
)
ON CONFLICT (publisher_id, year, month) DO UPDATE SET
    shared_in_ministry = EXCLUDED.shared_in_ministry,
    bible_studies = EXCLUDED.bible_studies,
    hours = EXCLUDED.hours,
    auxiliary_pioneer = EXCLUDED.auxiliary_pioneer,
    late = EXCLUDED.late,
    remarks = EXCLUDED.remarks,
    updated_at = now()
RETURNING id, publisher_id, year, month, shared_in_ministry, bible_studies,
    hours, auxiliary_pioneer, late, remarks, created_at, updated_at
`

type UpsertReportParams struct {
	PublisherID      uuid.UUID `json:"publisher_id"`
	Year             int16     `json:"year"`
	Month            int16     `json:"month"`
	SharedInMinistry bool      `json:"shared_in_ministry"`
	BibleStudies     int32     `json:"bible_studies"`
	Hours            *float64  `json:"hours"`
	AuxiliaryPioneer bool      `json:"auxiliary_pioneer"`
	Late             bool      `json:"late"`
	Remarks          string    `json:"remarks"`
}

func (q *Queries) UpsertReport(ctx context.Context, arg UpsertReportParams) (FieldServiceReport, error) {
	row := q.db.QueryRow(ctx, upsertReport,
		arg.PublisherID,
		arg.Year,
		arg.Month,
		arg.SharedInMinistry,
		arg.BibleStudies,
		arg.Hours,
		arg.AuxiliaryPioneer,
		arg.Late,
		arg.Remarks,
	)
	var i FieldServiceReport
	err := row.Scan(
		&i.ID,
		&i.PublisherID,
		&i.Year,
		&i.Month,
		&i.SharedInMinistry,
		&i.BibleStudies,
		&i.Hours,
		&i.AuxiliaryPioneer,
		&i.Late,
		&i.Remarks,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
